title: Kiran Mohammadi-Williams
description: "A personal portfolio"
logo_img: "/assets/img/logo.png"
profile_img: "/assets/img/profile_pic.png"

# Social Links
email: kyran.a.williams@gmail.com
github_username: kam535



# If your repo name follows the format "<user-name>.github.io", then leave the below blank.
# Otherwise, set its value as "/<repo-name>". ex) baseurl: /myblog
url: ''
baseurl: ''
safe: false
# Build settings
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-loading-lazy
  - jekyll-tidy
      
sass:
  style:            :compressed

privatelinks:
  title: Private or Broken Links
  msg: "The page you're looking for is either not available or private!"
  
collections:
    notes:
      output: true
      permalink: /note/:title

preferences:
  search:
    enabled: true
  wiki_style_link: 
    enabled: true
  pagepreview: 
    enabled: true
  backlinks:
    enabled: true

 homepage: 
    enabled: false


kramdown:
  input: GFM
  hard_wrap: true
  math_engine: katex
  smart_quotes: ["apos", "apos", "quot", "quot"]
  syntax_highlighter: rouge

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: Post
      permalink: /post/:title
      content-type: post
  - scope:
      path: ""
      type: notes
    values:
      layout: Post
      content-type: notes

exclude:
  - _notes/000 Inbox
  - _notes/200 Private
  - _notes/300 Templates
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
