title: "Kiran Mohammadi-Williams"
description: "A personal portfolio"
logo_img: "/assets/img/logo.png"
profile_img: "/assets/img/profile_pic.png"

# Social Links
email: kyran.a.williams@gmail.com
github_username: kam535

# Build settings
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-loading-lazy
  - jekyll-tidy

homepage:
  enabled: false
  
kramdown:
  input: GFM
  hard_wrap: true
  math_engine: katex
  smart_quotes: ["apos", "apos", "quot", "quot"]
  syntax_highlighter: rouge

preferences:
  search:
    enabled: true
  wiki_style_link: 
    enabled: true
  pagepreview: 
    enabled: true
  backlinks:
    enabled: true
    
exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
